name: chatbot-eval-lab

services:
  db:
    image: postgres:16-alpine
    container_name: gt-db
    environment:
      POSTGRES_DB: ${DB_NAME:-groundtruth}
      POSTGRES_USER: ${DB_USER:-gtuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-gtpass}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./services/groundtruth-db/init:/docker-entrypoint-initdb.d:ro
    ports:
      - "5432:5432"

  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    volumes:
      - qdrant_storage:/qdrant/storage
    ports:
      - "6333:6333"

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "11434:11434"

  orders-api:
    build:
      context: ./services/orders-api
    container_name: orders-api
    environment:
      DATABASE_URL: postgresql+psycopg://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME
    depends_on:
      - db
    ports:
      - "7001:8000"

  billing-api:
    build:
      context: ./services/billing-api
    container_name: billing-api
    environment:
      DATABASE_URL: postgresql+psycopg://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME
    depends_on:
      - db
    ports:
      - "7002:8000"

  inventory-api:
    build:
      context: ./services/inventory-api
    container_name: inventory-api
    environment:
      DATABASE_URL: postgresql+psycopg://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME
    depends_on:
      - db
    ports:
      - "7003:8000"

  policy-api:
    build:
      context: ./services/policy-api
    container_name: policy-api
    environment:
      DATABASE_URL: postgresql+psycopg://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME
    depends_on:
      - db
    ports:
      - "7004:8000"

  chatbot:
    build:
      context: ./apps/chatbot
    volumes:
      - ./data/rag_corpus:/app/data/rag_corpus:ro
    container_name: chatbot
    environment:
      ADMIN_TOKEN: "supersecret"
      OLLAMA_BASE_URL: http://ollama:11434
      MODEL_ID: ${MODEL_ID:-llama3.1:8b}
      QDRANT_URL: http://qdrant:6333
      DATABASE_URL: postgresql+psycopg://$DB_USER:$DB_PASSWORD@db:5432/$DB_NAME
      ORDERS_API_URL: http://orders-api:8000
      BILLING_API_URL: http://billing-api:8000
      INVENTORY_API_URL: http://inventory-api:8000
      POLICY_API_URL: http://policy-api:8000
      RAG_COLLECTION: ${RAG_COLLECTION:-docs}
    depends_on:
      - db
      - qdrant
      - ollama
      - orders-api
      - billing-api
      - inventory-api
      - policy-api
    ports:
      - "8000:8000"

 

  ui:
    build:
      context: ./ui
    volumes:
      - ./ui:/app
      - ./eval:/app/eval
    environment:
      CHATBOT_BASE_URL: http://chatbot:8000
      ADMIN_TOKEN: supersecret
      DB_URL: postgresql+psycopg://gtuser:gtpass@db:5432/groundtruth
    ports:
      - "8501:8501"
    depends_on:
      - chatbot

volumes:
  pgdata:
  qdrant_storage:
  ollama_models:

